on: workflow_call
jobs:
  ghtemplate:
    if: github.event.head_commit.message == 'Initial commit'
    runs-on: ubuntu-latest
    steps:
      - shell: cat {0}
        run: ${{ toJSON(github.event) }}